const kanjiGrade1 = [
  { kanji: "一", on: "イチ", kun: "ひと-つ", sens: "Un" },
  { kanji: "二", on: "ニ", kun: "ふた-つ", sens: "Deux" },
  { kanji: "三", on: "サン", kun: "みっ-つ", sens: "Trois" },
  { kanji: "四", on: "シ", kun: "よっ-つ", sens: "Quatre" },
  { kanji: "五", on: "ゴ", kun: "いつ-つ", sens: "Cinq" },
  { kanji: "六", on: "ロク", kun: "むっ-つ", sens: "Six" },
  { kanji: "七", on: "シチ", kun: "なな-つ", sens: "Sept" },
  { kanji: "八", on: "ハチ", kun: "やっ-つ", sens: "Huit" },
  { kanji: "九", on: "キュウ", kun: "ここの-つ", sens: "Neuf" },
  { kanji: "十", on: "ジュウ", kun: "とお", sens: "Dix" },
  { kanji: "百", on: "ヒャク", kun: "もも", sens: "Cent" },
  { kanji: "千", on: "セン", kun: "ち", sens: "Mille" },
  { kanji: "万", on: "マン", kun: "よろず", sens: "Dix mille" },
  { kanji: "円", on: "エン", kun: "まる-い", sens: "Yen / Cercle" },
  { kanji: "日", on: "ニチ", kun: "ひ", sens: "Jour / Soleil" },
  { kanji: "月", on: "ゲツ", kun: "つき", sens: "Mois / Lune" },
  { kanji: "火", on: "カ", kun: "ひ", sens: "Feu" },
  { kanji: "水", on: "スイ", kun: "みず", sens: "Eau" },
  { kanji: "木", on: "モク", kun: "き", sens: "Bois / Arbre" },
  { kanji: "金", on: "キン", kun: "かね", sens: "Or / Argent" },
  { kanji: "土", on: "ド", kun: "つち", sens: "Terre" },
  { kanji: "年", on: "ネン", kun: "とし", sens: "Année" },
  { kanji: "左", on: "サ", kun: "ひだり", sens: "Gauche" },
  { kanji: "右", on: "ウ", kun: "みぎ", sens: "Droite" },
  { kanji: "上", on: "ジョウ", kun: "うえ", sens: "Haut" },
  { kanji: "下", on: "ゲ", kun: "した", sens: "Bas" },
  { kanji: "中", on: "チュウ", kun: "なか", sens: "Milieu / Intérieur" },
  { kanji: "大", on: "ダイ", kun: "おお-きい", sens: "Grand" },
  { kanji: "小", on: "ショウ", kun: "ちい-さい", sens: "Petit" },
  { kanji: "口", on: "コウ", kun: "くち", sens: "Bouche" },
  { kanji: "目", on: "モク", kun: "め", sens: "Œil" },
  { kanji: "耳", on: "ジ", kun: "みみ", sens: "Oreille" },
  { kanji: "手", on: "シュ", kun: "て", sens: "Main" },
  { kanji: "足", on: "ソク", kun: "あし", sens: "Pied / Jambe" },
  { kanji: "人", on: "ジン", kun: "ひと", sens: "Personne" },
  { kanji: "子", on: "シ", kun: "こ", sens: "Enfant" },
  { kanji: "女", on: "ジョ", kun: "おんな", sens: "Femme" },
  { kanji: "男", on: "ダン", kun: "おとこ", sens: "Homme" },
  { kanji: "先", on: "セン", kun: "さき", sens: "Précédent" },
  { kanji: "生", on: "セイ", kun: "い-きる", sens: "Vie / Naissance" },
  { kanji: "学", on: "ガク", kun: "まな-ぶ", sens: "Étude" },
  { kanji: "校", on: "コウ", kun: "なし", sens: "École" },
  { kanji: "名", on: "メイ", kun: "な", sens: "Nom" },
  { kanji: "本", on: "ホン", kun: "もと", sens: "Livre / Origine" },
  { kanji: "文", on: "ブン", kun: "ふみ", sens: "Texte / Écrit" },
  { kanji: "字", on: "ジ", kun: "あざ", sens: "Caractère" },
  { kanji: "正", on: "セイ", kun: "ただ-しい", sens: "Correct" },
  { kanji: "立", on: "リツ", kun: "た-つ", sens: "Se tenir debout" },
  { kanji: "力", on: "リョク", kun: "ちから", sens: "Force / Puissance" },
  { kanji: "出", on: "シュツ", kun: "で-る", sens: "Sortir" },
  { kanji: "入", on: "ニュウ", kun: "はい-る", sens: "Entrer" },
  { kanji: "休", on: "キュウ", kun: "やす-む", sens: "Se reposer" },
  { kanji: "見", on: "ケン", kun: "み-る", sens: "Voir" },
  { kanji: "早", on: "ソウ", kun: "はや-い", sens: "Tôt / Rapide" },
  { kanji: "天", on: "テン", kun: "あめ", sens: "Ciel / Paradis" },
  { kanji: "気", on: "キ", kun: "いき", sens: "Esprit / Énergie" },
  { kanji: "雨", on: "ウ", kun: "あめ", sens: "Pluie" },
  { kanji: "空", on: "クウ", kun: "そら", sens: "Ciel / Vide" },
  { kanji: "白", on: "ハク", kun: "しろ", sens: "Blanc" },
  { kanji: "赤", on: "セキ", kun: "あか", sens: "Rouge" },
  { kanji: "青", on: "セイ", kun: "あお", sens: "Bleu" },
  { kanji: "山", on: "サン", kun: "やま", sens: "Montagne" },
  { kanji: "川", on: "セン", kun: "かわ", sens: "Rivière" },
  { kanji: "林", on: "リン", kun: "はやし", sens: "Bois" },
  { kanji: "森", on: "シン", kun: "もり", sens: "Forêt" },
  { kanji: "草", on: "ソウ", kun: "くさ", sens: "Herbe" },
  { kanji: "花", on: "カ", kun: "はな", sens: "Fleur" },
  { kanji: "竹", on: "チク", kun: "たけ", sens: "Bambou" },
  { kanji: "石", on: "セキ", kun: "いし", sens: "Pierre" },
  { kanji: "貝", on: "バイ", kun: "かい", sens: "Coquillage" },
  { kanji: "虫", on: "チュウ", kun: "むし", sens: "Insecte" },
  { kanji: "犬", on: "ケン", kun: "いぬ", sens: "Chien" },
  { kanji: "玉", on: "ギョク", kun: "たま", sens: "Balle / Gemme" },
  { kanji: "車", on: "シャ", kun: "くるま", sens: "Voiture / Véhicule" },
  { kanji: "糸", on: "シ", kun: "いと", sens: "Fil" },
  { kanji: "村", on: "ソン", kun: "むら", sens: "Village" },
  { kanji: "町", on: "チョウ", kun: "まち", sens: "Ville" },
  { kanji: "夕", on: "セキ", kun: "ゆう", sens: "Soir" },
  { kanji: "音", on: "オン", kun: "おと", sens: "Son" },
  { kanji: "王", on: "オウ", kun: "なし", sens: "Roi" }
];

const kanjiGrade2 = [
  { kanji: "引", on: "イン", kun: "ひ-く", sens: "Tirer" },
  { kanji: "羽", on: "ウ", kun: "は", sens: "Plume / Aile" },
  { kanji: "雲", on: "ウン", kun: "くも", sens: "Nuage" },
  { kanji: "園", on: "エン", kun: "その", sens: "Jardin" },
  { kanji: "遠", on: "エン", kun: "とお-い", sens: "Loin" },
  { kanji: "何", on: "カ", kun: "なに", sens: "Quoi" },
  { kanji: "科", on: "カ", kun: "なし", sens: "Science / Branche" },
  { kanji: "夏", on: "カ", kun: "なつ", sens: "Été" },
  { kanji: "家", on: "カ", kun: "いえ", sens: "Maison" },
  { kanji: "歌", on: "カ", kun: "うた", sens: "Chanter" },
  { kanji: "画", on: "ガ", kun: "えがく", sens: "Dessin / Trait" },
  { kanji: "回", on: "カイ", kun: "まわ-る", sens: "Fois / Tourner" },
  { kanji: "会", on: "カイ", kun: "あ-う", sens: "Rencontre / Société" },
  { kanji: "海", on: "カイ", kun: "うみ", sens: "Mer" },
  { kanji: "絵", on: "カイ", kun: "え", sens: "Image / Peinture" },
  { kanji: "外", on: "ガイ", kun: "そと", sens: "Extérieur" },
  { kanji: "角", on: "カク", kun: "かど", sens: "Angle / Corne" },
  { kanji: "楽", on: "ガク", kun: "たの-しい", sens: "Musique / Plaisir" },
  { kanji: "活", on: "カツ", kun: "い-きる", sens: "Vie / Activité" },
  { kanji: "間", on: "カン", kun: "あいだ", sens: "Intervalle / Entre" },
  { kanji: "丸", on: "ガン", kun: "まる", sens: "Rond" },
  { kanji: "岩", on: "ガン", kun: "いわ", sens: "Rocher" },
  { kanji: "顔", on: "ガン", kun: "かお", sens: "Visage" },
  { kanji: "汽", on: "キ", kun: "なし", sens: "Vapeur" },
  { kanji: "記", on: "キ", kun: "しる-す", sens: "Noter / Inscrire" },
  { kanji: "帰", on: "キ", kun: "かえ-る", sens: "Rentrer" },
  { kanji: "弓", on: "キュウ", kun: "ゆみ", sens: "Arc" },
  { kanji: "牛", on: "ギュウ", kun: "うし", sens: "Vache" },
  { kanji: "魚", on: "ギョ", kun: "さかな", sens: "Poisson" },
  { kanji: "京", on: "キョウ", kun: "みやこ", sens: "Capitale" },
  { kanji: "強", on: "キョウ", kun: "つよ-い", sens: "Fort" },
  { kanji: "教", on: "キョウ", kun: "おし-える", sens: "Enseigner" },
  { kanji: "近", on: "キン", kun: "ちか-い", sens: "Proche" },
  { kanji: "兄", on: "キョウ", kun: "あに", sens: "Grand frère" },
  { kanji: "形", on: "ケイ", kun: "かたち", sens: "Forme" },
  { kanji: "計", on: "ケイ", kun: "はか-る", sens: "Mesurer / Plan" },
  { kanji: "元", on: "ゲン", kun: "もと", sens: "Origine / Base" },
  { kanji: "言", on: "ゲン", kun: "い-う", sens: "Dire" },
  { kanji: "原", on: "ゲン", kun: "はら", sens: "Plaine / Champ" },
  { kanji: "戸", on: "コ", kun: "と", sens: "Porte" },
  { kanji: "古", on: "コ", kun: "ふる-い", sens: "Vieux" },
  { kanji: "午", on: "ゴ", kun: "なし", sens: "Midi" },
  { kanji: "後", on: "ゴ", kun: "あと", sens: "Après / Derrière" },
  { kanji: "語", on: "ゴ", kun: "かた-る", sens: "Langue / Parler" },
  { kanji: "工", on: "コウ", kun: "なし", sens: "Artisanat / Travail" },
  { kanji: "公", on: "コウ", kun: "おおやけ", sens: "Public" },
  { kanji: "広", on: "コウ", kun: "ひろ-い", sens: "Large" },
  { kanji: "交", on: "コウ", kun: "まじ-わる", sens: "Échange / Intersection" },
  { kanji: "光", on: "コウ", kun: "ひかり", sens: "Lumière" },
  { kanji: "考", on: "コウ", kun: "かんが-える", sens: "Réfléchir" },
  { kanji: "行", on: "コウ", kun: "い-く", sens: "Aller" },
  { kanji: "高", on: "コウ", kun: "たか-い", sens: "Haut / Cher" },
  { kanji: "黄", on: "コウ", kun: "き", sens: "Jaune" },
  { kanji: "合", on: "ゴウ", kun: "あ-う", sens: "S'unir / Ajuster" },
  { kanji: "谷", on: "コク", kun: "たに", sens: "Vallée" },
  { kanji: "国", on: "コク", kun: "くに", sens: "Pays" },
  { kanji: "黒", on: "コク", kun: "くろ", sens: "Noir" },
  { kanji: "今", on: "コン", kun: "いま", sens: "Maintenant" },
  { kanji: "才", on: "サイ", kun: "なし", sens: "Talent / Âge" },
  { kanji: "細", on: "サイ", kun: "ほそ-い", sens: "Fin / Mince" },
  { kanji: "作", on: "サク", kun: "つく-る", sens: "Fabriquer" },
  { kanji: "算", on: "サン", kun: "なし", sens: "Calcul" },
  { kanji: "止", on: "シ", kun: "と-まる", sens: "S'arrêter" },
  { kanji: "市", on: "シ", kun: "いち", sens: "Ville / Marché" },
  { kanji: "矢", on: "シ", kun: "や", sens: "Flèche" },
  { kanji: "姉", on: "シ", kun: "あね", sens: "Grande sœur" },
  { kanji: "思", on: "シ", kun: "おも-う", sens: "Penser" },
  { kanji: "紙", on: "シ", kun: "かみ", sens: "Papier" },
  { kanji: "寺", on: "ジ", kun: "てら", sens: "Temple" },
  { kanji: "自", on: "ジ", kun: "みずか-ら", sens: "Soi-même" },
  { kanji: "時", on: "ジ", kun: "とき", sens: "Temps / Heure" },
  { kanji: "室", on: "シツ", kun: "むろ", sens: "Chambre / Salle" },
  { kanji: "社", on: "シャ", kun: "やしろ", sens: "Société / Sanctuaire" },
  { kanji: "弱", on: "ジャク", kun: "よわ-い", sens: "Faible" },
  { kanji: "首", on: "シュ", kun: "くび", sens: "Cou / Chef" },
  { kanji: "秋", on: "シュウ", kun: "あき", sens: "Automne" },
  { kanji: "週", on: "シュウ", kun: "なし", sens: "Semaine" },
  { kanji: "春", on: "シュン", kun: "はる", sens: "Printemps" },
  { kanji: "書", on: "ショ", kun: "か-く", sens: "Écrire" },
  { kanji: "少", on: "ショウ", kun: "すく-ない", sens: "Peu" },
  { kanji: "場", on: "ジョウ", kun: "ば", sens: "Lieu" },
  { kanji: "食", on: "ショク", kun: "た-べる", sens: "Manger" },
  { kanji: "新", on: "シン", kun: "あたら-しい", sens: "Nouveau" },
  { kanji: "心", on: "シン", kun: "こころ", sens: "Cœur" },
  { kanji: "親", on: "シン", kun: "おや", sens: "Parent / Intime" },
  { kanji: "図", on: "ズ", kun: "はか-る", sens: "Schéma / Dessin" },
  { kanji: "数", on: "スウ", kun: "かず", sens: "Nombre" },
  { kanji: "西", on: "セイ", kun: "にし", sens: "Ouest" },
  { kanji: "声", on: "セイ", kun: "こえ", sens: "Voix" },
  { kanji: "星", on: "セイ", kun: "ほし", sens: "Étoile" },
  { kanji: "晴", on: "セイ", kun: "は-れる", sens: "Beau temps" },
  { kanji: "切", on: "セツ", kun: "き-る", sens: "Couper" },
  { kanji: "雪", on: "セツ", kun: "ゆき", sens: "Neige" },
  { kanji: "船", on: "セン", kun: "ふね", sens: "Bateau" },
  { kanji: "線", on: "セン", kun: "なし", sens: "Ligne" },
  { kanji: "前", on: "ゼン", kun: "まえ", sens: "Avant / Devant" },
  { kanji: "組", on: "ソ", kun: "くみ", sens: "Groupe / Équipe" },
  { kanji: "走", on: "ソウ", kun: "はし-る", sens: "Courir" },
  { kanji: "多", on: "タ", kun: "おお-い", sens: "Beaucoup" },
  { kanji: "太", on: "タイ", kun: "ふと-い", sens: "Gros / Épais" },
  { kanji: "体", on: "タイ", kun: "からだ", sens: "Corps" },
  { kanji: "台", on: "ダイ", kun: "なし", sens: "Support / Socle" },
  { kanji: "地", on: "チ", kun: "なし", sens: "Terre / Sol" },
  { kanji: "池", on: "チ", kun: "いけ", sens: "Étang" },
  { kanji: "知", on: "チ", kun: "し-る", sens: "Savoir" },
  { kanji: "茶", on: "チャ", kun: "なし", sens: "Thé" },
  { kanji: "昼", on: "チュウ", kun: "ひる", sens: "Midi / Déjeuner" },
  { kanji: "長", on: "チョウ", kun: "なが-い", sens: "Long / Chef" },
  { kanji: "鳥", on: "チョウ", kun: "とり", sens: "Oiseau" },
  { kanji: "朝", on: "チョウ", kun: "あさ", sens: "Matin" },
  { kanji: "直", on: "チョク", kun: "なお-す", sens: "Réparer / Direct" },
  { kanji: "通", on: "ツウ", kun: "とお-る", sens: "Passer / Communiquer" },
  { kanji: "弟", on: "テイ", kun: "おとうと", sens: "Petit frère" },
  { kanji: "店", on: "テン", kun: "みせ", sens: "Magasin" },
  { kanji: "点", on: "テン", kun: "なし", sens: "Point" },
  { kanji: "電", on: "デン", kun: "なし", sens: "Électricité" },
  { kanji: "刀", on: "トウ", kun: "かたな", sens: "Sabre" },
  { kanji: "冬", on: "トウ", kun: "ふゆ", sens: "Hiver" },
  { kanji: "当", on: "トウ", kun: "あ-たる", sens: "Frapper / Atteindre" },
  { kanji: "東", on: "トウ", kun: "ひがし", sens: "Est" },
  { kanji: "答", on: "トウ", kun: "こた-える", sens: "Réponse" },
  { kanji: "頭", on: "トウ", kun: "あたま", sens: "Tête" },
  { kanji: "同", on: "ドウ", kun: "おな-じ", sens: "Même" },
  { kanji: "道", on: "ドウ", kun: "みち", sens: "Chemin" },
  { kanji: "読", on: "ドク", kun: "よ-む", sens: "Lire" },
  { kanji: "内", on: "ナイ", kun: "うち", sens: "Intérieur" },
  { kanji: "南", on: "ナン", kun: "みなみ", sens: "Sud" },
  { kanji: "肉", on: "ニク", kun: "なし", sens: "Viande" },
  { kanji: "馬", on: "バ", kun: "うま", sens: "Cheval" },
  { kanji: "売", on: "バイ", kun: "う-る", sens: "Vendre" },
  { kanji: "買", on: "バイ", kun: "か-う", sens: "Acheter" },
  { kanji: "麦", on: "バク", kun: "むぎ", sens: "Blé / Orge" },
  { kanji: "半", on: "ハン", kun: "なか-ば", sens: "Moitié" },
  { kanji: "番", on: "バン", kun: "なし", sens: "Numéro / Tour" },
  { kanji: "父", on: "フ", kun: "ちち", sens: "Père" },
  { kanji: "風", on: "フウ", kun: "かぜ", sens: "Vent" },
  { kanji: "分", on: "ブン", kun: "わ-かる", sens: "Minute / Diviser" },
  { kanji: "聞", on: "ブン", kun: "き-く", sens: "Entendre" },
  { kanji: "米", on: "ベイ", kun: "こめ", sens: "Riz" },
  { kanji: "歩", on: "ホ", kun: "ある-く", sens: "Marcher" },
  { kanji: "母", on: "ボ", kun: "はは", sens: "Mère" },
  { kanji: "方", on: "ホウ", kun: "かた", sens: "Direction" },
  { kanji: "毎", on: "マイ", kun: "なし", sens: "Chaque" },
  { kanji: "妹", on: "マイ", kun: "いもうと", sens: "Petite sœur" },
  { kanji: "明", on: "メイ", kun: "あか-るい", sens: "Clair / Lumineux" },
  { kanji: "鳴", on: "メイ", kun: "な-く", sens: "Crier / Sonner" },
  { kanji: "毛", on: "モウ", kun: "け", sens: "Poil / Cheveu" },
  { kanji: "門", on: "モン", kun: "かど", sens: "Portail" },
  { kanji: "夜", on: "ヤ", kun: "よ", sens: "Nuit" },
  { kanji: "野", on: "ヤ", kun: "の", sens: "Champ / Sauvage" },
  { kanji: "友", on: "ユウ", kun: "とも", sens: "Ami" },
  { kanji: "用", on: "ヨウ", kun: "もち-いる", sens: "Utilisation" },
  { kanji: "曜", on: "ヨウ", kun: "なし", sens: "Jour de la semaine" },
  { kanji: "来", on: "ライ", kun: "く-る", sens: "Venir" },
  { kanji: "里", on: "リ", kun: "さと", sens: "Village" },
  { kanji: "理", on: "リ", kun: "なし", sens: "Raison / Logique" },
  { kanji: "話", on: "ワ", kun: "はな-す", sens: "Parler" },
  { kanji: "原", on: "ゲン", kun: "はら", sens: "Plaine / Champ" },
  { kanji: "台", on: "ダイ", kun: "なし", sens: "Support / Socle" },
  { kanji: "北", on: "ホク", kun: "きた", sens: "Nord" },
];

const kanjiGrade3 = [
  { kanji: "悪", on: "アク", kun: "わる-い", sens: "Mauvais / Méchant" },
  { kanji: "安", on: "アン", kun: "やす-い", sens: "Bon marché / Paisible" },
  { kanji: "暗", on: "アン", kun: "くら-い", sens: "Sombre / Obscur" },
  { kanji: "医", on: "イ", kun: "なし", sens: "Médecine / Docteur" },
  { kanji: "委", on: "イ", kun: "ゆだ-ねる", sens: "Confier / Commission" },
  { kanji: "意", on: "イ", kun: "なし", sens: "Idée / Intention" },
  { kanji: "育", on: "イク", kun: "そだ-てる", sens: "Élever / Éduquer" },
  { kanji: "員", on: "イン", kun: "なし", sens: "Membre / Employé" },
  { kanji: "院", on: "イン", kun: "なし", sens: "Institution / Temple" },
  { kanji: "飲", on: "イン", kun: "の-む", sens: "Boire" },
  { kanji: "運", on: "ウン", kun: "はこ-ぶ", sens: "Transporter / Chance" },
  { kanji: "泳", on: "エイ", kun: "およ-ぐ", sens: "Nager" },
  { kanji: "駅", on: "エキ", kun: "なし", sens: "Gare" },
  { kanji: "央", on: "オウ", kun: "なし", sens: "Centre / Milieu" },
  { kanji: "横", on: "オウ", kun: "よこ", sens: "Côté / Horizontal" },
  { kanji: "屋", on: "オク", kun: "や", sens: "Toit / Magasin" },
  { kanji: "温", on: "オン", kun: "あたた-かい", sens: "Chaud (liquide/température)" },
  { kanji: "化", on: "カ", kun: "ば-ける", sens: "Changer / Transformer" },
  { kanji: "荷", on: "カ", kun: "に", sens: "Bagage / Charge" },
  { kanji: "界", on: "カイ", kun: "なし", sens: "Monde / Limite" },
  { kanji: "開", on: "カイ", kun: "あ-ける", sens: "Ouvrir" },
  { kanji: "階", on: "カイ", kun: "なし", sens: "Étage / Rang" },
  { kanji: "寒", on: "カン", kun: "さむ-い", sens: "Froid (météo)" },
  { kanji: "感", on: "カン", kun: "なし", sens: "Sentiment / Ressentir" },
  { kanji: "漢", on: "カン", kun: "なし", sens: "Chine / Kanji" },
  { kanji: "館", on: "カン", kun: "やかた", sens: "Bâtiment / Manoir" },
  { kanji: "岸", on: "ガン", kun: "きし", sens: "Rive / Côte" },
  { kanji: "起", on: "キ", kun: "お-きる", sens: "Se lever / Se produire" },
  { kanji: "期", on: "キ", kun: "なし", sens: "Période / Terme" },
  { kanji: "客", on: "キャク", kun: "なし", sens: "Client / Invité" },
  { kanji: "究", on: "キュウ", kun: "きわ-める", sens: "Recherche / Étudier" },
  { kanji: "急", on: "キュウ", kun: "いそ-ぐ", sens: "Urgent / Se dépêcher" },
  { kanji: "級", on: "キュウ", kun: "なし", sens: "Classe / Niveau" },
  { kanji: "宮", on: "キュウ", kun: "みや", sens: "Palais / Sanctuaire" },
  { kanji: "球", on: "キュウ", kun: "たま", sens: "Balle / Sphère" },
  { kanji: "去", on: "キョ", kun: "さ-る", sens: "Passé / Quitter" },
  { kanji: "橋", on: "キョウ", kun: "はし", sens: "Pont" },
  { kanji: "業", on: "ギョウ", kun: "わざ", sens: "Affaire / Travail" },
  { kanji: "曲", on: "キョク", kun: "ま-がる", sens: "Courber / Musique" },
  { kanji: "局", on: "キョク", kun: "なし", sens: "Bureau / Département" },
  { kanji: "銀", on: "ギン", kun: "なし", sens: "Argent (métal)" },
  { kanji: "区", on: "ク", kun: "なし", sens: "Quartier / District" },
  { kanji: "苦", on: "ク", kun: "くる-しい", sens: "Souffrance / Amer" },
  { kanji: "具", on: "グ", kun: "なし", sens: "Outil / Ingrédient" },
  { kanji: "君", on: "クン", kun: "きみ", sens: "Tu / Toi (familier)" },
  { kanji: "係", on: "ケイ", kun: "かか-る", sens: "Responsable / Lien" },
  { kanji: "軽", on: "ケイ", kun: "かる-い", sens: "Léger" },
  { kanji: "血", on: "ケツ", kun: "ち", sens: "Sang" },
  { kanji: "決", on: "ケツ", kun: "き-める", sens: "Décider" },
  { kanji: "研", on: "ケン", kun: "と-ぐ", sens: "Recherche / Aiguiser" },
  { kanji: "県", on: "ケン", kun: "なし", sens: "Préfecture" },
  { kanji: "庫", on: "コ", kun: "くら", sens: "Entrepôt / Garage" },
  { kanji: "湖", on: "コ", kun: "みずうみ", sens: "Lac" },
  { kanji: "向", on: "コウ", kun: "む-く", sens: "S'orienter / Vers" },
  { kanji: "幸", on: "コウ", kun: "しあわ-せ", sens: "Bonheur / Chance" },
  { kanji: "港", on: "コウ", kun: "みなと", sens: "Port" },
  { kanji: "号", on: "ゴウ", kun: "なし", sens: "Numéro / Signal" },
  { kanji: "根", on: "コン", kun: "ね", sens: "Racine" },
  { kanji: "祭", on: "サイ", kun: "まつ-り", sens: "Fête / Festival" },
    { kanji: "皿", on: "なし", kun: "さら", sens: "Assiette" },
  { kanji: "仕", on: "シ", kun: "つか-える", sens: "Servir / Faire" },
  { kanji: "死", on: "シ", kun: "し-ぬ", sens: "Mort" },
  { kanji: "使", on: "シ", kun: "つか-う", sens: "Utiliser" },
  { kanji: "始", on: "シ", kun: "はじ-める", sens: "Commencer" },
  { kanji: "指", on: "シ", kun: "ゆび", sens: "Doigt / Montrer" },
  { kanji: "歯", on: "シ", kun: "は", sens: "Dent" },
  { kanji: "詩", on: "シ", kun: "なし", sens: "Poème" },
  { kanji: "次", on: "ジ", kun: "つぎ", sens: "Suivant" },
  { kanji: "事", on: "ジ", kun: "こと", sens: "Chose / Fait" },
  { kanji: "持", on: "ジ", kun: "も-つ", sens: "Tenir / Posséder" },
  { kanji: "式", on: "シキ", kun: "なし", sens: "Style / Cérémonie" },
  { kanji: "実", on: "ジツ", kun: "み", sens: "Réalité / Fruit" },
  { kanji: "写", on: "シャ", kun: "うつ-す", sens: "Copier / Photographier" },
  { kanji: "者", on: "シャ", kun: "もの", sens: "Quelqu'un (profession)" },
  { kanji: "主", on: "シュ", kun: "ぬし", sens: "Maître / Principal" },
  { kanji: "守", on: "シュ", kun: "まも-る", sens: "Protéger / Garder" },
  { kanji: "取", on: "シュ", kun: "と-る", sens: "Prendre" },
  { kanji: "酒", on: "シュ", kun: "さけ", sens: "Alcool / Saké" },
  { kanji: "受", on: "ジュ", kun: "う-ける", sens: "Recevoir" },
  { kanji: "州", on: "シュウ", kun: "す", sens: "État / Province" },
  { kanji: "拾", on: "シュウ", kun: "ひろ-う", sens: "Ramasser" },
  { kanji: "終", on: "シュウ", kun: "お-わる", sens: "Fin / Terminer" },
  { kanji: "習", on: "シュウ", kun: "なら-う", sens: "Apprendre" },
  { kanji: "集", on: "シュウ", kun: "あつ-まる", sens: "Rassembler" },
  { kanji: "住", on: "ジュウ", kun: "す-む", sens: "Habiter" },
  { kanji: "重", on: "ジュウ", kun: "おも-い", sens: "Lourd / Important" },
  { kanji: "宿", on: "シュク", kun: "やど", sens: "Auberge / Logement" },
  { kanji: "所", on: "ショ", kun: "ところ", sens: "Lieu / Place" },
  { kanji: "暑", on: "ショ", kun: "あつ-い", sens: "Chaud (climat)" },
  { kanji: "助", on: "ジョ", kun: "たす-ける", sens: "Aider / Secourir" },
  { kanji: "昭", on: "ショウ", kun: "なし", sens: "Lumineux (ère Showa)" },
  { kanji: "消", on: "ショウ", kun: "き-える", sens: "S'éteindre / Effacer" },
  { kanji: "商", on: "ショウ", kun: "あきな-う", sens: "Commerce" },
  { kanji: "章", on: "ショウ", kun: "なし", sens: "Chapitre / Médaille" },
  { kanji: "勝", on: "ショウ", kun: "か-つ", sens: "Gagner" },
  { kanji: "乗", on: "ジョウ", kun: "の-る", sens: "Monter (véhicule)" },
  { kanji: "植", on: "ショク", kun: "う-える", sens: "Planter" },
  { kanji: "申", on: "シン", kun: "もう-す", sens: "Dire (humble)" },
  { kanji: "身", on: "シン", kun: "み", sens: "Corps / Soi-même" },
  { kanji: "神", on: "シン", kun: "かみ", sens: "Dieu / Esprit" },
  { kanji: "真", on: "シン", kun: "ま", sens: "Vrai / Pur" },
  { kanji: "深", on: "シン", kun: "ふか-い", sens: "Profond" },
  { kanji: "進", on: "シン", kun: "すす-む", sens: "Avancer" },
  { kanji: "世", on: "セイ", kun: "よ", sens: "Monde / Génération" },
  { kanji: "整", on: "セイ", kun: "ととの-える", sens: "Organiser / Ranger" },
  { kanji: "昔", on: "セキ", kun: "むかし", sens: "Autrefois" },
  { kanji: "全", on: "ゼン", kun: "まった-く", sens: "Tout / Entier" },
  { kanji: "相", on: "ソウ", kun: "あい", sens: "Aspect / Mutuel" },
  { kanji: "送", on: "ソウ", kun: "おく-る", sens: "Envoyer" },
  { kanji: "想", on: "ソウ", kun: "なし", sens: "Pensée / Imagination" },
  { kanji: "息", on: "ソク", kun: "いき", sens: "Souffle / Respiration" },
  { kanji: "速", on: "ソク", kun: "はや-い", sens: "Rapide" },
  { kanji: "族", on: "ゾク", kun: "なし", sens: "Famille / Tribu" },
  { kanji: "他", on: "タ", kun: "ほか", sens: "Autre" },
  { kanji: "打", on: "ダ", kun: "う-つ", sens: "Frapper" },
  { kanji: "対", on: "タイ", kun: "なし", sens: "Face à / Contre" },
  { kanji: "待", on: "タイ", kun: "ま-つ", sens: "Attendre" },
  { kanji: "代", on: "ダイ", kun: "か-わる", sens: "Remplacer / Génération" },
  { kanji: "第", on: "ダイ", kun: "なし", sens: "Numéro (ordinal)" },
  { kanji: "題", on: "ダイ", kun: "なし", sens: "Sujet / Titre" },
  { kanji: "炭", on: "タン", kun: "すみ", sens: "Charbon" },
  { kanji: "短", on: "タン", kun: "みじか-い", sens: "Court" },
  { kanji: "談", on: "ダン", kun: "なし", sens: "Discuter" },
  { kanji: "着", on: "チャク", kun: "き-る", sens: "Arriver / Porter (vêtement)" },
  { kanji: "注", on: "チュウ", kun: "そそ-ぐ", sens: "Verser / Attention" },
  { kanji: "柱", on: "チュウ", kun: "はしら", sens: "Pilier / Poteau" },
  { kanji: "帳", on: "チョウ", kun: "なし", sens: "Registre / Carnet" },
  { kanji: "調", on: "チョウ", kun: "しら-べる", sens: "Enquêter / Ton" },
  { kanji: "追", on: "ツイ", kun: "お-う", sens: "Poursuivre" },
  { kanji: "丁", on: "テイ", kun: "なし", sens: "Compteur / Rue" },
  { kanji: "定", on: "テイ", kun: "さだ-める", sens: "Fixer / Décider" },
  { kanji: "庭", on: "テイ", kun: "にわ", sens: "Jardin" },
  { kanji: "笛", on: "テキ", kun: "ふえ", sens: "Flûte / Sifflet" },
  { kanji: "鉄", on: "テツ", kun: "なし", sens: "Fer" },
  { kanji: "転", on: "テン", kun: "ころ-ぶ", sens: "Rouler / Tomber" },
  { kanji: "都", on: "ト", kun: "みやこ", sens: "Métropole / Capitale" },
  { kanji: "度", on: "ド", kun: "たび", sens: "Degré / Fois" },
  { kanji: "投", on: "トウ", kun: "な-げる", sens: "Jeter" },
  { kanji: "豆", on: "トウ", kun: "まめ", sens: "Haricot / Pois" },
  { kanji: "島", on: "トウ", kun: "しま", sens: "Île" },
  { kanji: "湯", on: "トウ", kun: "ゆ", sens: "Eau chaude / Bain" },
  { kanji: "登", on: "トウ", kun: "のぼ-る", sens: "Grimper" },
  { kanji: "等", on: "トウ", kun: "ひと-しい", sens: "Classe / Égal" },
  { kanji: "動", on: "ドウ", kun: "うご-く", sens: "Bouger" },
  { kanji: "童", on: "ドウ", kun: "わらべ", sens: "Enfant" },
  { kanji: "農", on: "ノウ", kun: "なし", sens: "Agriculture" },
  { kanji: "波", on: "ハ", kun: "なみ", sens: "Vague" },
  { kanji: "配", on: "ハイ", kun: "くば-る", sens: "Distribuer" },
  { kanji: "倍", on: "バイ", kun: "なし", sens: "Double / Fois" },
{ kanji: "畑", on: "なし", kun: "はたけ", sens: "Champ / Potager" },
  { kanji: "発", on: "ハツ", kun: "なし", sens: "Départ / Émettre" },
  { kanji: "反", on: "ハン", kun: "そ-る", sens: "Anti- / Opposer" },
  { kanji: "坂", on: "ハン", kun: "さか", sens: "Pente / Colline" },
  { kanji: "板", on: "ハン", kun: "いた", sens: "Planche" },
  { kanji: "皮", on: "ヒ", kun: "かわ", sens: "Peau / Cuir" },
  { kanji: "悲", on: "ヒ", kun: "かな-しい", sens: "Triste" },
  { kanji: "美", on: "ビ", kun: "うつく-しい", sens: "Beau / Beauté" },
  { kanji: "鼻", on: "ビ", kun: "はな", sens: "Nez" },
  { kanji: "筆", on: "ヒツ", kun: "ふで", sens: "Pinceau / Écriture" },
  { kanji: "氷", on: "ヒョウ", kun: "こおり", sens: "Glace" },
  { kanji: "秒", on: "ビョウ", kun: "なし", sens: "Seconde" },
  { kanji: "病", on: "ビョウ", kun: "や-まい", sens: "Maladie" },
  { kanji: "品", on: "ヒン", kun: "しな", sens: "Article / Qualité" },
  { kanji: "負", on: "フ", kun: "ま-ける", sens: "Perdre / Porter" },
  { kanji: "部", on: "ブ", kun: "なし", sens: "Partie / Section" },
  { kanji: "服", on: "フク", kun: "なし", sens: "Vêtement" },
  { kanji: "福", on: "フク", kun: "なし", sens: "Fortune / Bonheur" },
  { kanji: "物", on: "ブツ", kun: "もの", sens: "Objet / Chose" },
  { kanji: "平", on: "ヘイ", kun: "たい-ら", sens: "Plat / Paix" },
  { kanji: "兵", on: "ヘイ", kun: "なし", sens: "Soldat" },
  { kanji: "別", on: "ベツ", kun: "わか-れる", sens: "Séparer / Autre" },
  { kanji: "勉", on: "ベン", kun: "なし", sens: "Effort" },
  { kanji: "放", on: "ホウ", kun: "はな-す", sens: "Relâcher" },
  { kanji: "法", on: "ホウ", kun: "なし", sens: "Loi / Méthode" },
  { kanji: "忘", on: "ボウ", kun: "わす-れる", sens: "Oublier" },
  { kanji: "忙", on: "ボウ", kun: "いそが-しい", sens: "Occupé" },
  { kanji: "暴", on: "ボウ", kun: "あば-れる", sens: "Violent / Se déchaîner" },
  { kanji: "牧", on: "ボク", kun: "まき", sens: "Pâturage" },
  { kanji: "末", on: "マツ", kun: "すえ", sens: "Fin / Extrémité" },
  { kanji: "満", on: "マン", kun: "み-ちる", sens: "Plein / Remplir" },
  { kanji: "味", on: "ミ", kun: "あじ", sens: "Goût / Saveur" },
  { kanji: "未", on: "ミ", kun: "まだ", sens: "Pas encore" },
  { kanji: "命", on: "メイ", kun: "いのち", sens: "Vie / Destin" },
  { kanji: "面", on: "メン", kun: "おもて", sens: "Face / Surface" },
  { kanji: "問", on: "モン", kun: "と-う", sens: "Question" },
  { kanji: "役", on: "ヤク", kun: "なし", sens: "Rôle / Service" },
  { kanji: "薬", on: "ヤク", kun: "くすり", sens: "Médicament" },
  { kanji: "由", on: "ユ", kun: "よし", sens: "Raison / Cause" },
  { kanji: "油", on: "ユ", kun: "あぶら", sens: "Huile" },
  { kanji: "有", on: "ユウ", kun: "あ-る", sens: "Exister / Avoir" },
  { kanji: "遊", on: "ユウ", kun: "あそ-ぶ", sens: "Jouer" },
  { kanji: "予", on: "ヨ", kun: "あらかじ-め", sens: "À l'avance" },
  { kanji: "羊", on: "ヨウ", kun: "ひつじ", sens: "Mouton" },
  { kanji: "洋", on: "ヨウ", kun: "なし", sens: "Océan / Occidental" },
  { kanji: "葉", on: "ヨウ", kun: "は", sens: "Feuille" },
  { kanji: "陽", on: "ヨウ", kun: "なし", sens: "Soleil / Positif" },
  { kanji: "様", on: "ヨウ", kun: "さま", sens: "Apparence / Monsieur/Madame" },
  { kanji: "落", on: "ラク", kun: "お-ちる", sens: "Tomber" },
  { kanji: "流", on: "リュウ", kun: "なが-れる", sens: "Couler" },
  { kanji: "旅", on: "リョ", kun: "たび", sens: "Voyage" },
  { kanji: "両", on: "リョウ", kun: "なし", sens: "Les deux" },
  { kanji: "緑", on: "リョク", kun: "みどり", sens: "Vert" },
  { kanji: "礼", on: "レイ", kun: "なし", sens: "Salut / Courtoisie" },
  { kanji: "列", on: "レツ", kun: "なし", sens: "File / Rangée" },
  { kanji: "練", on: "レン", kun: "ね-る", sens: "S'entraîner" },
  { kanji: "路", on: "ロ", kun: "みち", sens: "Route / Chemin" },
  { kanji: "和", on: "ワ", kun: "やわ-らぐ", sens: "Harmonie / Paix / Japon" },
  { kanji: "返", on: "ヘン", kun: "かえ-す", sens: "Rendre / Répondre" },
    { kanji: "勉", on: "ベン", kun: "つと-める", sens: "S'efforcer / Étudier" },
    { kanji: "題", on: "ダイ", kun: "なし", sens: "Sujet / Titre / Problème" },
    { kanji: "指", on: "シ", kun: "ゆび", sens: "Doigt / Montrer" },
    { kanji: "助", on: "ジョ", kun: "たす-ける", sens: "Aider / Secourir" },
    { kanji: "研", on: "ケン", kun: "と-ぐ", sens: "Rechercher / Polir" },
];


// Fusion globale
const dictionnaireKanjis = [...kanjiGrade1, ...kanjiGrade2, ...kanjiGrade3];